#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export JAVA_HOME=/opt/java/jdk
export TERMINAL=termite
export PATH=$JAVA_HOME/bin:/home/lukas/.gem/ruby/2.4.0/bin:$PATH
export LD_LIBRARY_PATH=/opt/cuda/lib64/:$LD_LIBRARY_PATH
