#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt sharehistory

###-tns-completion-start-###
if [ -f /home/lukas/.tnsrc ]; then 
    source /home/lukas/.tnsrc 
fi
###-tns-completion-end-###
