#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# For Strg+Shift+t support
if [[ $TERM == xterm-termite ]]; then
  source "/etc/profile.d/vte.sh"
fi

# Customize to your needs...

unsetopt sharehistory

export NVM_DIR="$HOME/.nvm"

alias master="cd ~/git/masterarbeit"
alias music="nohup google-chrome-stable --app=https://music.amazon.de/stations 2>&1 > /dev/null&"
alias open=xdg-open
alias toggle="python ~/git/toggl/parser.py"

alias en_nvm="source $NVM_DIR/nvm.sh && source $NVM_DIR/bash_completion"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export SWIVM_DIR="/home/lukas/.swivm"
#[ -s "$SWIVM_DIR/swivm.sh" ] && . "$SWIVM_DIR/swivm.sh"  # This loads swivm
alias enable_prolog="source $SWIVM_DIR/swivm.sh"

alias ipython="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"
alias pycharm="/home/lukas/programms/pycharm-2017.1.5/bin/pycharm.sh"
